[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "1.1.1"
num-traits = "0.2.19"
numeric-array = "0.6.1"
rayon = "1.10.0"

[profile.release]
opt-level = 3
lto = true
