name: check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - .github/workflows/*.yml
      - Cargo.toml
      - src/**

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: rustup update --no-self-update stable && rustup default stable
      - run: cargo fmt --check
      - run: cargo check --release --locked

      - run: cargo build --release --locked
      - run: |
          cp target/release/macmon macmon
          tar czf macmon-${{ github.ref_name }}.tar.gz readme.md LICENSE macmon
          ls -lah | grep macmon
        id: archive

      - uses: actions/upload-artifact@v4
        with:
          name: macmon-${{ github.ref_name }}.tar.gz
          path: macmon-${{ github.ref_name }}.tar.gz
          retention-days: 7
